volumes:
  postgres_data:
    driver: local
  

networks:
  airflow:
    driver: bridge
  airflow-spark:
    driver: bridge

services:
  spark-master:
    build: 
      context: .
      dockerfile: spark.Dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./tests:/opt/bitnami/spark/tests
      - ./data:/opt/bitnami/spark/spark-warehouse
    networks:
      - airflow-spark

  spark-worker-1:
    build: 
      context: .
      dockerfile: spark.Dockerfile
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - airflow-spark

  spark-worker-2:
    build: 
      context: .
      dockerfile: spark.Dockerfile
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8082:8081"
    networks:
      - airflow-spark

  dremio:
    container_name: dremio
    image: dremio/dremio-oss
    volumes:
      - ./data:/mnt/data
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
      - "45678:45678"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow

  airflow-webserver:
    build: 
      context: .
      dockerfile: airflow.Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    ports:
      - "9091:8080"
    command: webserver
    networks:
      - airflow
      - airflow-spark

  airflow-scheduler:
    build: 
      context: .
      dockerfile: airflow.Dockerfile
    restart: always
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    command: scheduler
    networks:
      - airflow
      - airflow-spark
